name: Auto Update Daily
on:
    schedule:
        - cron: '0 23 */1 * *'

jobs:
    update-css:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2.0.0


            - name: Download File
              uses: carlosperate/download-file-action@v1.0.0
              with:
                file-url: https://lcwebsite.cn/aka/bing-images-url.aspx
                location: ./2022/
            

            - name: Log Information
              run: echo "The file was downloaded to ${{ steps.download-file.outputs.file-path }}"


            - name: Upload file
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                export FILE_NAME="$(TZ=UTC-8 date +%Y%m).txt"
                export MESSAGE="Auto update."
                export SHA=$( git rev-parse main:$FILE_NAME )
                gh api --method PUT /repos/:owner/:repo/contents/$FILE_NAME \
                  --field message="$MESSAGE" \
                  --field content=@<( base64 -i $FILE_NAME ) \
                  --field branch="main" \
                  --field sha="$SHA"