name: Auto Update Daily
on:
  schedule:
    - cron: '0 14 */1 * *' # UTC+8 22:00
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Download File
        shell: pwsh
        run: |
          $cstNow = [TimeZoneInfo]::ConvertTimeFromUtc([DateTime]::UtcNow, [TimeZoneInfo]::FindSystemTimeZoneById("China Standard Time"))
          if (!(Test-Path $cstNow.Year)) {
            mkdir $cstNow.Year
          }
          iwr "https://api.lcwebsite.cn/Cache/Bing/$($cstNow.ToString("yyyyMM")).txt" -OutFile "$($cstNow.Year)/$($cstNow.ToString("yyyyMM")).txt"


      - name: Upload file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export FILE_NAME="$(TZ=UTC-8 date +%Y)/$(TZ=UTC-8 date +%Y%m).txt"
          export MESSAGE="Auto update."
          export SHA=$( git rev-parse main:$FILE_NAME )
          gh api --method PUT /repos/:owner/:repo/contents/$FILE_NAME \
            --field message="$MESSAGE" \
            --field content=@<( base64 -i $FILE_NAME ) \
            --field branch="main" \
            --field sha="$SHA"